services:
  - type: web
    name: aquaculture-api
    env: python
    plan: free
    buildCommand: "pip install -r summative/API/requirements.txt"
    startCommand: "uvicorn summative.API.prediction:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
